# Generated by Django 4.0.5 on 2022-06-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
