# Generated by Django 3.2.13 on 2022-06-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20220616_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'coord_lng', 'coord_lat')},
        ),
    ]
