# Generated by Django 3.2.13 on 2022-06-24 13:40

from django.db import migrations


def remove_null(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all().iterator():
        is_changed = False
        if place.description_short is None:
            place.description_short = ''
            is_changed = True
        if place.description_long is None:
            place.description_long = ''
            is_changed = True
        if is_changed:
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_placeimage_image'),
    ]

    operations = [
        migrations.RunPython(remove_null),
    ]
